# Generated by Django 4.2.13 on 2024-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('product_owner', 'Product Owner'), ('user', 'user')], max_length=20),
        ),
    ]
