# Generated by Django 4.2.13 on 2024-05-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
